FROM node:20.11.1

WORKDIR /usr/src/app

COPY package*.json ./


COPY . .

RUN npm install

RUN npm run build

EXPOSE 80

CMD ["npm", "start"]

FROM nginx:latest

COPY --from=0 /usr/src/app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
