CREATE DATABASE IF NOT EXISTS PRO0YECTO1;

USE PROYECTO1;

CREATE TABLE MemoriaRAM (
    id INT PRIMARY KEY AUTO_INCREMENT,
    uso DECIMAL(5,2),
    total DECIMAL(5,2),
    enUso DECIMAL(5,2),
    porcentaje DECIMAL(5,2),
    libre DECIMAL(5,2),
    fechaHora DATETIME
);