apiVersion: v1
kind: Service
metadata:
  namespace: namespace-proyecto2
  name: service-producer
spec:
  ports:
  - name: producer-go
    port: 5003
    targetPort: 5003
  - name: producer-rust
    port: 5004
    targetPort: 5004
  selector:
      name: deploy-producer
  type: LoadBalancer