apiVersion: v1
kind: Service
metadata:
  namespace: namespace-proyecto2
  name: service-consumer
spec:
  ports:
  - name: consumer-port
    port: 5005
    targetPort: 5005
  selector:
      name: deploy-consumer
  type: NodePort